import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Head from 'next/head';

import MouseMoveEffect from "./components/mouse-move-effect";
import { Nav } from "./components/nav";
import { Footer } from "./components/footer";

import { SocialNetworksI } from "@/interfaces/social-networks";

import { API } from '@/api'

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Hudson Farias",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  const response = await API.get('/social_networks')
  const data: SocialNetworksI = await response.json()

  return (
    <html lang="pt-br">

      <Head>
        {/* Preconnect for Google Fonts */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />

        {/* Stylesheet for DM Sans font */}
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=DM+Sans:ital,opsz,wght@0,9..40,100..1000;1,9..40,100..1000&display=swap"
        />
      </Head>

      <body className={`antialiased font-dmSans h-screen grid grid-rows-[1fr_14fr] overflow-hidden`}>
      {/* <body className={`${geistSans.variable} ${geistMono.variable} antialiased font-dmSans h-screen grid grid-rows-[1fr_14fr] overflow-hidden`}> */}
        <Nav socialNetworks={data.social_networks_header} />
        <div className="overflow-auto scrollbar-thin scrollbar-thumb-blue-500/10 scrollbar-track-slate-500/10">
          {children}
          <MouseMoveEffect />
          <Footer socialNetworks={data.social_networks_footer} />
        </div>
      </body>
    </html>
  );
}
